package com.project.back_end.services;

import com.project.back_end.models.Admin;
import com.project.back_end.models.Doctor;
import com.project.back_end.models.Patient;
import com.project.back_end.repo.AdminRepository;
import com.project.back_end.repo.DoctorRepository;
import com.project.back_end.repo.PatientRepository;
import io.jsonwebtoken.JwtBuilder;
import io.jsonwebtoken.JwtException;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.time.LocalDateTime;
import java.util.Date;

/**
 * The TokenService class provides functionality for generating, validating, and parsing JWT tokens
 * for different user roles within the application. It manages token creation, extracts user identifiers,
 * and ensures secure authentication and authorization by checking user existence in the corresponding repositories.
 * This service is a Spring component and interacts with Admin, Doctor, and Patient repositories for role-based token validation.
 */
@Component
public class TokenService {
    // 1. **@Component Annotation**
    // The @Component annotation marks this class as a Spring component, meaning Spring will manage it as a bean within its application context.
    // This allows the class to be injected into other Spring-managed components (like services or controllers) where it's needed.

    // 2. **Constructor Injection for Dependencies**
    // The constructor injects dependencies for `AdminRepository`, `DoctorRepository`, and `PatientRepository`,
    // allowing the service to interact with the database and validate users based on their role (admin, doctor, or patient).
    // Constructor injection ensures that the class is initialized with all required dependencies, promoting immutability and making the class testable.
    private AdminRepository adminRepository;
    private DoctorRepository doctorRepository;
    private PatientRepository patientRepository;


    // 3. **getSigningKey Method**
    // This method retrieves the HMAC SHA key used to sign JWT tokens.
    // It uses the `jwt.secret` value, which is provided from an external source (like application properties).
    // The `Keys.hmacShaKeyFor()` method converts the secret key string into a valid `SecretKey` for signing and verification of JWTs.
    /**
     * The secret key used for signing JWT tokens.
     * <p>
     * This key is retrieved from the application properties file
     * (e.g., application.yml or application.properties) where it
     * should be securely stored. Ensure that this secret is kept
     * confidential and not hard-coded in the source code.
     * <p>
     * Example configuration in application.properties:
     * jwt.secret=mySuperSecretKey
     */
    @Value("${jwt.secret}")
    private String jwtSecret;

    // 4. **generateToken Method**
    // This method generates a JWT token for a user based on their email.
    // - The `subject` of the token is set to the user's email, which is used as an identifier.
    // - The `issuedAt` is set to the current date and time.
    // - The `expiration` is set to 7 days from the issue date, ensuring the token expires after one week.
    // - The token is signed using the signing key generated by `getSigningKey()`, making it secure and tamper-proof.
    // The method returns the JWT token as a string.

    /**
     * Generates a JWT token for a given user identifier (usually an email).
     * <p>
     * This method creates a token that includes the following attributes:
     * - **Subject**: The user's identifier (email).
     * - **Issued At**: The current date and time, indicating when the token was created.
     * - **Expiration**: The date and time when the token will expire, set to 7 days from the issued date.
     * <p>
     * The token is signed using a secret key (retrieved from application properties)
     * to ensure its integrity and authenticity. This key must remain confidential
     * and is derived from the `getSigningKey()` method.
     *
     * @param identifier The user's identifier (email) for which the token is generated.
     * @return A compact JWT token as a String.
     * <p>
     * * Example usage:
     * * String token = tokenService.generateToken("user@example.com");
     * * System.out.println("Generated Token: " + token);
     *
     */
    String generateToken(String identifier) {

        LocalDateTime now = LocalDateTime.now();
        LocalDateTime expiration = now.plusDays(7);

        Date issuedAt = Date.from(Instant.from(now));
        Date expirationAt = Date.from(Instant.from(expiration));

        JwtBuilder token = Jwts.builder()
                .subject(identifier)
                .issuedAt(issuedAt)
                .expiration(expirationAt)
                .signWith(getSigningKey());

        return token.compact();
    }

    /**
     * Retrieves the HMAC SHA key used for signing and verifying JWT tokens.
     * <p>
     * This method converts the secret key string (configured in the application properties)
     * into a valid `SecretKey` object using the HMAC SHA algorithm.
     * The key is automatically populated from the `jwt.secret` property during
     * the initialization of the TokenService component. This ensures that the key
     * is securely managed and not hard-coded in the source code.
     * <p>
     * The `jwt.secret` should be defined in your application.properties file as follows:
     * jwt.secret=mySuperSecretKey
     * <p>
     * Ensure this key is kept confidential and is not hard-coded in the source code.
     *
     * @return A `SecretKey` object used for signing and verifying JWT tokens.
     * <p>
     * * Example usage:
     * * SecretKey signingKey = tokenService.getSigningKey();
     * * System.out.println("Signing Key: " + signingKey);
     *
     */
    SecretKey getSigningKey() {
        return Keys.hmacShaKeyFor(jwtSecret.getBytes(StandardCharsets.UTF_8));
    }


    // 5. **extractEmail Method**
    // This method extracts the user's email (subject) from the provided JWT token.
    // - The token is first verified using the signing key to ensure it hasn’t been tampered with.
    // - After verification, the token is parsed, and the subject (which represents the email) is extracted.
    // This method allows the application to retrieve the user's identity (email) from the token for further use.

    /**
     * Extracts the user's identifier (usually an email) from a given JWT token.
     * <p>
     * This method performs the following steps:
     * - Verifies the token's integrity using the signing key (from `getSigningKey()`) to ensure it hasn’t been tampered with.
     * - Parses the token to retrieve the payload, which contains the subject (the user's identifier).
     * <p>
     * If the token is invalid or cannot be parsed, a JwtException will be thrown.
     *
     * @param token The JWT token from which the identifier needs to be extracted.
     * @return The user's identifier (email) as a String.
     * @throws JwtException If the token is invalid or cannot be parsed.
     * <p>
     * * Example Usage:
     * * String email = tokenService.extractIdentifier(token);
     * * System.out.println("Extracted Email: " + email);
     */
    String extractIdentifier(String token) {
        return Jwts.parser()
                .verifyWith(getSigningKey())
                .build().parseSignedClaims(token)
                .getPayload()
                .getSubject();
    }

    // 6. **validateToken Method**
    // This method validates whether a provided JWT token is valid for a specific user role (admin, doctor, or patient).
    // - It first extracts the email from the token using the `extractEmail()` method.
    // - Depending on the role (`admin`, `doctor`, or `patient`), it checks the corresponding repository (AdminRepository, DoctorRepository, or PatientRepository)
    //   to see if a user with the extracted email exists.
    // - If a match is found for the specified user role, it returns true, indicating the token is valid.
    // - If the role or user does not exist, it returns false, indicating the token is invalid.
    // - The method gracefully handles any errors by returning false if the token is invalid or an exception occurs.
    // This ensures secure access control based on the user's role and their existence in the system.

    /**
     * Validates a token for a given user type by extracting the identifier from the token
     * and checking if a corresponding user exists in the repository.
     * <p>
     * This method performs the following:
     * - Extracts the user's identifier from the token.
     * - Checks if a user with the extracted email exists in the appropriate repository
     * (Admin, Doctor, or Patient) based on the specified role.
     * - Returns true if a valid user is found; otherwise, returns false.
     * <p>
     * If the token is invalid, the method will gracefully handle the error and return false.
     *
     * @param token the authentication token to validate
     * @param user  the user type ("admin", "doctor", or "patient")
     * @return true if the token is valid for the specified user type; false otherwise
     * <p>
     * * Example Usage:
     * * boolean isValid = tokenService.validateToken(token, "doctor");
     * * System.out.println("Is Token Valid: " + isValid);
     */
    boolean validateToken(String token, String user) {
        String subject = extractIdentifier(token);

        // Worst case, if the token can not be found:
        if (subject.isEmpty()) {
            return false;
        }

        try {
            switch (user) {
                case "admin":
                    Admin admin = adminRepository.findByUsername(subject);
                    return admin != null;
                case "doctor":
                    Doctor doctor = doctorRepository.findByEmail(subject);
                    return doctor != null;
                case "patient":
                    Patient patient = patientRepository.findByEmail(subject);
                    return patient != null;
                default:
                    // if the given user type was none of the expected:
                    return false;
            }
        } catch (Exception e) {
            return false;
        }
    }
}
